server:
  port: 8080

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: villager
    password: 0000
    url: jdbc:mysql://localhost:3306/countrydb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource